### ISSUE TITLE
Errors in ROS1 Melodic

### ISSUE THREAD

**Issue by rscova** [aws-robotics/aws-robomaker-hospital-world#1]
Hi,
I am using ROS1 Melodic, I have followed the ROS Launch with Gazebo viewer (without a robot) instructions but using catkin_make. I got this error ¿do you know how to solve it? Thank you in advance!

`[Err] [Node.cc:105] No namespace found`
`[Err] [Node.cc:105] No namespace found`
`[Err] [InsertModelWidget.cc:405] Missing model.config for model "/opt/ros/melodic/share/turtlebot3_gazebo/models/turtlebot3_autorace"`
`[Wrn] [ColladaLoader.cc:1432] Unable to add material[]`
`[Wrn] [ColladaLoader.cc:1432] Unable to add material[]`
`[ INFO] [1596578205.252982887]: waitForService: Service [/gazebo/set_physics_properties] is now available.`
`[Wrn] [ColladaLoader.cc:1432] Unable to add material[]`
`[ INFO] [1596578205.268863584]: Physics dynamic reconfigure ready.`
`[Wrn] [ColladaLoader.cc:1432] Unable to add material[]`
`[Err] [Material.cc:96] Unable to find texture[Carts_Wheels_Diffuse] in path[/home/saul/catkin_ws/src/aws-robomaker-hospital-world-master/fuel_models/CGMClassic/meshes/]`
`[Err] [OBJLoader.cc:79] WARN: Material file [ /home/saul/catkin_ws/src/aws-robomaker-hospital-world-master/fuel_models/VisitorChair/meshes/VisitorChair_Col.mtl ] not found. Created a default material.`
`terminate called after throwing an instance of 'std::logic_error'`
`  what():  basic_string::_M_construct null not valid`
`[Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call`
`[Err] [Connection.cc:546] Connection[6] Closed during Read`
`[Err] [TransportIface.cc:375] Unable to read from master`
`[Err] [GLWidget.cc:881] Unable to connect to a running Gazebo master.`
`Aborted (core dumped)`
`[gazebo-1] process has died [pid 16134, exit code 134, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver --verbose -e ode /home/saul/catkin_ws/src/aws-robomaker-hospital-world-master/worlds/hospital.world __name:=gazebo __log:=/home/saul/.ros/log/5f33bc96-d69d-11ea-9378-6014b3b58fb9/gazebo-1.log].`
`log file: /home/saul/.ros/log/5f33bc96-d69d-11ea-9378-6014b3b58fb9/gazebo-1*.log`
`[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/world/user_camera/pose, deleting message. This warning is printed only once.`

**Comment by iamrajee** [comment]
> Hi,
> I am using ROS1 Melodic, ...

@rscova  I'm also getting the same error on melodic.

**Comment by ojasjoshi** [comment]
Thank you for raising the issue. We are looking into it. 

Can you please provide more information regarding your OS, rosversion, gazebo version, GPU/CPU hardware?

**Comment by iamrajee** [comment]
> Can you please provide more information regarding your OS, rosversion, gazebo version, GPU/CPU hardware?

 Thank you for your response, here are my system specs:

**OS:** Ubuntu 18.04
**ROS Version:** Melodic
**Gazebo Version:** 9.0.0
**GPU:** GTX1660Ti
**CPU:** Intel Core i7 9th Gen

> [Err] [Material.cc:96] Unable to find texture[Carts_Wheels_Diffuse] in path[/home/saul/catkin_ws/src/aws-robomaker-hospital-world-master/fuel_models/CGMClassic/meshes/]

Error appear as fuel_models `VisitorChair`,  `OpScrubs` and `PatientWheelChair` is missing `*_Col.mtl` file. If we comment out all instances of these models in world file, then its working perfectly.

> [Err] [Material.cc:96] Unable to find texture[Carts_Wheels_Diffuse] in path[/home/saul/catkin_ws/src/aws-robomaker-hospital-world-master/fuel_models/CGMClassic/meshes/]

renaming `aws-robomaker-hospital-world/fuel_models/CGMClassic/meshes/Carts_Wheels_Diffuse.png` to renaming `aws-robomaker-hospital-world/fuel_models/CGMClassic/meshes/Carts_Wheels_Diffuse` will resolves the error.

Here is link to the [gist](https://gist.github.com/iamrajee/4a6a534d2cbc7eea6742d881c1653a16), after resolving the errors in above mentioned way. Although, after this I'm able to visualise the world in gazebo, I'm still getting few errors and warning as below:
```
[Err] [Node.cc:105] No namespace found
[Err] [Node.cc:105] No namespace found
[Err] [Node.cc:105] No namespace found
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/opt/ros/melodic/share/turtlebot3_gazebo/models/turtlebot3_autorace"
[Wrn] [ColladaLoader.cc:1432] Unable to add material[]
[Err] [REST.cc:205] Error in REST request
[Wrn] [ColladaLoader.cc:1805] Triangle input semantic: 'TEXCOORD' is currently not supported
```

@rscova @ojasjoshi

**Comment by ojasjoshi** [comment]
@iamrajee just to clarify, gzerver process does not die in your case correct?

**Comment by ojasjoshi** [comment]
The issue seems to be stemming from bad fuel models referenced from the ignition server.
Follow-up issues have been created and are being tracked:
ignitionrobotics/ign-fuel-tools#117
ignitionrobotics/ign-fuel-tools#118

We will update once we have more information. Thanks!

**Comment by wangvnn** [comment]
I have this error when loading to gazebo with verbose flag enabled:

[Err] [Material.cc:96] Unable to find texture[Carts_Wheels_Diffuse] in path[/home/ANT.AMAZON.COM/kenvink/workspace/simengine/aws-robomaker-hospital-world/fuel_models/CGMClassic/meshes/]
[Err] [OBJLoader.cc:79] WARN: Material file [ /home/ANT.AMAZON.COM/kenvink/workspace/simengine/aws-robomaker-hospital-world/fuel_models/VisitorChair/meshes/VisitorChair_Col.mtl ] not found. Created a default material.

OS: Ubuntu 18.04
ROS Version: Melodic
Gazebo Version: 9.0.0
GPU: Intel UHD
CPU: Intel® Core™ i7-9750H CPU @ 2.60GHz × 12

**Comment by ojasjoshi** [comment]
https://github.com/aws-robotics/aws-robomaker-hospital-world/pull/4 should fix this now.
