### ISSUE TITLE
Question about world layout sizing

### ISSUE THREAD

**Issue by h4zman** [aws-robotics/aws-robomaker-hospital-world#14]
Hi, good day everyone. May I know the sizing of this hospital world?  I tried to find the info but can't seem to find the answer. Would be glad if someone will be able to help me with this question. 

Thanks in advance.

**Comment by cheng-kevin** [comment]
Hi, just wanted to follow up with more details.  By sizing do you mean the units?  If so, the poses are specified in meters.

**Comment by h4zman** [comment]
Hi kevin, I'm trying to figure out the hospital size layout ( Width x length ) in m.

**Comment by ahtsan** [comment]
Gazebo uses SI unit (see [here](https://answers.gazebosim.org//question/8497/standard-units-of-measure-and-coordinate-conventions-in-gazebo/)), the unit is meters. You can run gazebo with the world, and measure it in the GUI.
Let us know if you have difficulties measuring it.
