### ISSUE TITLE
complete remove from ubuntu

### ISSUE THREAD

**Issue by samsu0192** [aws-robotics/aws-robomaker-hospital-world#16]
after try to use setup.sh following the tutorial, every other world I open will have a hospital world inside. then I try to delete the git folder from the catkin_ws, and now my whole gazebo totally spoiled. How could I reverse the changes/settings?

**Comment by cheng-kevin** [comment]
For gazebo support you can try visiting https://answers.gazebosim.org/questions/ .  For your original problem, try reversing the firs t step of modifying your launch file.
